// packages/demos/angular/src/app/simple-nav/page-two/page-two.ts
import { Component, ViewEncapsulation } from '@angular/core';
import { Location } from '@angular/common';
import { NavController } from '@ionic/angular';


@Component({
  selector: 'page-two',
  template: `
  <ion-page>
    <ion-header>
      <ion-toolbar>
        <ion-title>Page Two</ion-title>
      </ion-toolbar>
    </ion-header>
    <ion-content padding>
      Page Two - {{ts}}
      <div>
        <ion-button (click)="pushPageThreeComponent()">Go to Page Three</ion-button>
      </div>
      <div>
        <ion-button (click)="goBack()">Go Back</ion-button>
      </div>
    </ion-content>
  </ion-page>
  `
})
export class PageTwo {

  constructor(private navController: NavController) {
  }

  pushPageThreeComponent() {
    this.navController.push('/simple-nav/page-three');
  }

  goBack() {
    this.navController.pop();
  }
}

// packages/core/src/components/nav/page-two.tsx
import { Component, Element } from '@stencil/core';

@Component({
  tag: 'page-two'
})
export class PageTwo {

  @Element() element: HTMLElement;

  componentDidEnter() {
    console.log('page two did enter');
  }

  nextPage() {
    const nav = this.element.closest('ion-nav') as any;
    nav.push('page-three');
  }

  pop() {
    const nav = this.element.closest('ion-nav') as any;
    nav.pop();
  }

  render() {
    return [<ion-header>
      <ion-toolbar>
        <ion-title>Page Two</ion-title>
      </ion-toolbar>
    </ion-header>,
    <ion-content fullscreen={true}>
      Page Two Content
      <div>
        <ion-button onClick={() => this.nextPage()}>Go to Page Three</ion-button>
      </div>
      <div>
        <ion-button onClick={() => this.pop()}>Go Back</ion-button>
      </div>
    </ion-content>
    ];
  }
}
