// packages/ionic-angular/src/components/segment/segment.ts
import { AfterContentInit, ContentChildren, Directive, ElementRef, Optional, QueryList, Renderer } from '@angular/core';
import { NgControl } from '@angular/forms';

import { Config } from '../../config/config';
import { BaseInput } from '../../util/base-input';
import { assert } from '../../util/util';
import { SegmentButton } from './segment-button';

/**
 * @name Segment
 * @description
 * A Segment is a group of buttons, sometimes known as Segmented Controls, that allow the user to interact with a compact group of a number of controls.
 * Segments provide functionality similar to tabs, selecting one will unselect all others. You should use a tab bar instead of a segmented control when you want to let the user move back and forth between distinct pages in your app.
 * You could use Angular's `ngModel` or `FormBuilder` API. For an overview on how `FormBuilder` works, checkout [Angular Forms](http://learnangular2.com/forms/), or [Angular FormBuilder](https://angular.io/docs/ts/latest/api/forms/index/FormBuilder-class.html)
 *
 *
 * ```html
 * <!-- Segment in a header -->
 * <ion-header>
 *   <ion-toolbar>
 *     <ion-segment [(ngModel)]="icons" color="secondary">
 *       <ion-segment-button value="camera">
 *         <ion-icon name="camera"></ion-icon>
 *       </ion-segment-button>
 *       <ion-segment-button value="bookmark">
 *         <ion-icon name="bookmark"></ion-icon>
 *       </ion-segment-button>
 *     </ion-segment>
 *   </ion-toolbar>
 * </ion-header>
 *
 * <ion-content>
 *   <!-- Segment in content -->
 *   <ion-segment [(ngModel)]="relationship" color="primary" (ionChange)="segmentChanged($event)">
 *     <ion-segment-button value="friends">
 *       Friends
 *     </ion-segment-button>
 *     <ion-segment-button value="enemies">
 *       Enemies
 *     </ion-segment-button>
 *   </ion-segment>
 *
 *   <!-- Segment in a form -->
 *   <form [formGroup]="myForm">
 *     <ion-segment formControlName="mapStyle" color="danger">
 *       <ion-segment-button value="standard">
 *         Standard
 *       </ion-segment-button>
 *       <ion-segment-button value="hybrid">
 *         Hybrid
 *       </ion-segment-button>
 *       <ion-segment-button value="sat">
 *         Satellite
 *       </ion-segment-button>
 *     </ion-segment>
 *   </form>
 * </ion-content>
 * ```
 *
 *
 * @demo /docs/demos/src/segment/
 * @see {@link /docs/components#segment Segment Component Docs}
 * @see [Angular Forms](http://learnangular2.com/forms/)
 */
@Directive({
  selector: 'ion-segment',
  host: {
    '[class.segment-disabled]': '_disabled'
  }
})
export class Segment extends BaseInput<string> implements AfterContentInit {

  /**
   * @hidden
   */
  @ContentChildren(SegmentButton) _buttons: QueryList<SegmentButton>;

  constructor(
    config: Config,
    elementRef: ElementRef,
    renderer: Renderer,
    @Optional() ngControl: NgControl
  ) {
    super(config, elementRef, renderer, 'segment', null, null, null, ngControl);
  }

  /**
   * @hidden
   */
  ngAfterContentInit() {
    this._initialize();
    this._buttons.forEach(button => {
      button.ionSelect.subscribe((selectedButton: any) => this.value = selectedButton.value);
    });
  }

  /**
   * @hidden
   * Write a new value to the element.
   */
  _inputUpdated() {
    if (!this._buttons) {
      assert(false, 'buttons are undefined');
      return;
    }
    const buttons = this._buttons.toArray();
    const value = this.value;
    for (var button of buttons) {
      button.isActive = (button.value === value);
    }
  }


}

// packages/core/src/components/segment/segment.tsx
import { Component, h, Listen, Prop, PropDidChange } from '@stencil/core';

import { HostElement, SegmentButtonEvent, VNodeData } from '../../utils/interfaces';


/**
 * @name Segment
 * @description
 * A Segment is a group of buttons, sometimes known as Segmented Controls, that allow the user to interact with a compact group of a number of controls.
 * Segments provide functionality similar to tabs, selecting one will unselect all others. You should use a tab bar instead of a segmented control when you want to let the user move back and forth between distinct pages in your app.
 * You could use Angular's `ngModel` or `FormBuilder` API. For an overview on how `FormBuilder` works, checkout [Angular Forms](http://learnangular2.com/forms/), or [Angular FormBuilder](https://angular.io/docs/ts/latest/api/forms/index/FormBuilder-class.html)
 *
 *
 * ```html
 * <!-- Segment in a header -->
 * <ion-header>
 *   <ion-toolbar>
 *     <ion-segment [(ngModel)]="icons" color="secondary">
 *       <ion-segment-button value="camera">
 *         <ion-icon name="camera"></ion-icon>
 *       </ion-segment-button>
 *       <ion-segment-button value="bookmark">
 *         <ion-icon name="bookmark"></ion-icon>
 *       </ion-segment-button>
 *     </ion-segment>
 *   </ion-toolbar>
 * </ion-header>
 *
 * <ion-content>
 *   <!-- Segment in content -->
 *   <ion-segment [(ngModel)]="relationship" color="primary" (ionChange)="segmentChanged($event)">
 *     <ion-segment-button value="friends">
 *       Friends
 *     </ion-segment-button>
 *     <ion-segment-button value="enemies">
 *       Enemies
 *     </ion-segment-button>
 *   </ion-segment>
 *
 *   <!-- Segment in a form -->
 *   <form [formGroup]="myForm">
 *     <ion-segment formControlName="mapStyle" color="danger">
 *       <ion-segment-button value="standard">
 *         Standard
 *       </ion-segment-button>
 *       <ion-segment-button value="hybrid">
 *         Hybrid
 *       </ion-segment-button>
 *       <ion-segment-button value="sat">
 *         Satellite
 *       </ion-segment-button>
 *     </ion-segment>
 *   </form>
 * </ion-content>
 * ```
 *
 *
 * @demo /docs/demos/src/segment/
 * @see {@link /docs/components#segment Segment Component Docs}
 * @see [Angular Forms](http://learnangular2.com/forms/)
 */
@Component({
  tag: 'ion-segment',
  styleUrls: {
    ios: 'segment.ios.scss',
    md: 'segment.md.scss',
    wp: 'segment.wp.scss'
  },
  host: {
    theme: 'segment'
  }
})
export class Segment {
  buttons: NodeListOf<HostElement>;
  $el: HTMLElement;

  @Prop({ state: true }) disabled: boolean = false;

  @Prop({ state: true }) value: string;

  @PropDidChange('value')
  changed(val: string) {
    this.selectButton(val);
  }

  ionViewDidLoad() {
    this.buttons = this.$el.querySelectorAll('ion-segment-button') as NodeListOf<HostElement>;

    for (var i = 0; i < this.buttons.length; i++) {
      const button = this.buttons[i].$instance;

      button.activated = (button.value === this.value);

      // If there is no value set on the segment and a button
      // is checked we should activate it
      if (!this.value && button.checked) {
        button.activated = button.checked;
      }
    }
  }

  @Listen('ionClick')
  segmentClick(ev: SegmentButtonEvent) {
    let selectedButton = ev.detail.segmentButton;

    this.value = selectedButton.value;
    this.selectButton(this.value);
  }

  selectButton(val: string) {
    for (var i = 0; i < this.buttons.length; i++) {
      const button = this.buttons[i].$instance;
      button.activated = (button.value === val);
    }

    // returning true tells the renderer to queue an update
    return true;
  }

  hostData(): VNodeData {
    return {
      class: {
        'segment-disabled': this.disabled
      }
    };
  }

  render() {
    return <slot></slot>;
  }
}
