// packages/ionic-angular/src/components/range/range-knob.ts
import { Component, EventEmitter, HostListener, Input, Output } from '@angular/core';

import { KEY_LEFT, KEY_RIGHT, KEY_UP, KEY_DOWN } from '../../platform/key';

/**
 * @hidden
 */
@Component({
  selector: '.range-knob-handle',
  template:
    '<div class="range-pin" *ngIf="pin" role="presentation">{{val}}</div>' +
    '<div class="range-knob" role="presentation"></div>',
  host: {
    '[class.range-knob-pressed]': 'pressed',
    '[class.range-knob-min]': 'val===min||val===undefined',
    '[class.range-knob-max]': 'val===max',
    '[style.left]': '_x',
    '[attr.aria-valuenow]': 'val',
    '[attr.aria-valuemin]': 'min',
    '[attr.aria-valuemax]': 'max',
    '[attr.aria-disabled]': 'disabled',
    '[attr.aria-labelledby]': 'labelId',
    '[tabindex]': 'disabled?-1:0',
    'role': 'slider'
  }
})
export class RangeKnob {
  _x: string;

  @Input() set ratio(r: number) {
    this._x = `${r * 100}%`;
  }
  @Input() pressed: boolean;
  @Input() pin: boolean;
  @Input() min: number;
  @Input() max: number;
  @Input() val: number;
  @Input() disabled: boolean;
  @Input() labelId: string;

  @Output() ionIncrease = new EventEmitter();
  @Output() ionDecrease = new EventEmitter();

  @HostListener('keydown', ['$event']) _keyup(ev: KeyboardEvent) {
    const keyCode = ev.keyCode;
    if (keyCode === KEY_LEFT || keyCode === KEY_DOWN) {
      console.debug(`range-knob, decrease, keyCode: ${keyCode}`);
      this.ionDecrease.emit();
      ev.preventDefault();
      ev.stopPropagation();

    } else if (keyCode === KEY_RIGHT || keyCode === KEY_UP) {
      console.debug(`range-knob, increase, keyCode: ${keyCode}`);
      this.ionIncrease.emit();
      ev.preventDefault();
      ev.stopPropagation();
    }
  }
}

// core/src/components/range-knob/range-knob.tsx
import { Component, Event, EventEmitter, Listen, Prop } from '@stencil/core';

@Component({
  tag: `ion-range-knob`
})
export class RangeKnob {

  @Prop() pressed = false;
  @Prop() pin = false;
  @Prop() min!: number;
  @Prop() max!: number;
  @Prop() val!: number;
  @Prop() disabled = false;
  @Prop() labelId!: string;
  @Prop() knob!: string;
  @Prop() ratio!: number;

  @Event() ionIncrease!: EventEmitter;
  @Event() ionDecrease!: EventEmitter;

  @Listen('keydown')
  handleKeyBoard(ev: KeyboardEvent) {
    const keyCode = ev.keyCode;
    if (keyCode === KEY_LEFT || keyCode === KEY_DOWN) {
      this.ionDecrease.emit({isIncrease: false, knob: this.knob});
      ev.preventDefault();
      ev.stopPropagation();
    } else if (keyCode === KEY_RIGHT || keyCode === KEY_UP) {
      this.ionIncrease.emit({isIncrease: true, knob: this.knob});
      ev.preventDefault();
      ev.stopPropagation();
    }
  }

  leftPos(val: number) {
    return `${val * 100}%`;
  }

  hostData() {
    return {
      class: {
        'range-knob-pressed': this.pressed,
        'range-knob-min': this.val === this.min || this.val === undefined,
        'range-knob-max': this.val === this.max
      },
      style: {
        'left': this.leftPos(this.ratio)
      },
      'role': 'slider',
      'tabindex': this.disabled ? -1 : 0,
      'aria-valuemin': this.min,
      'aria-valuemax': this.max,
      'aria-disabled': this.disabled,
      'aria-labelledby': this.labelId,
      'aria-valuenow': this.val
    };
  }

  render() {
    if (this.pin) {
      return [
        <div class="range-pin" role="presentation">{this.val}</div>,
        <div class="range-knob" role="presentation" />
      ];
    }
    return <div class="range-knob" role="presentation" />;
  }
}

export const KEY_LEFT = 37;
export const KEY_UP = 38;
export const KEY_RIGHT = 39;
export const KEY_DOWN = 40;
