// demos/angular/src/app/simple-nav/page-two/page-two.ts
import { Component, ViewEncapsulation } from '@angular/core';
import { Location } from '@angular/common';


@Component({
  selector: 'page-two',
  template: `
    <ion-header>
      <ion-toolbar>
        <ion-title>Page Two</ion-title>
      </ion-toolbar>
    </ion-header>
    <ion-content padding>
      Page Two - {{ts}}
      <div>
        <ion-button>Go to Page Three</ion-button>
      </div>
      <div>
        <ion-button>Go Back</ion-button>
      </div>
    </ion-content>
  `
})
export class PageTwo {

}

// packages/core/scripts/test-components/src/components/page-two/page-two.tsx
import { Component } from '@stencil/core';

@Component({
  tag: 'page-two',
})
export class PageTwo {

  render() {
    return [
      <ion-header>
        <ion-toolbar>
          <ion-title>Page Two</ion-title>
        </ion-toolbar>
      </ion-header>,
      <ion-content>
        this is page two
      </ion-content>
    ];
  }
}
