// packages/core/src/components/platform/platform.tsx
import { Component, Element, Method, Prop } from '@stencil/core';

import { PlatformConfig } from '../../index';
import { isCordova } from '../../global/platform-utils';

@Component({
  tag: 'ion-platform',
})
export class Platform {

  @Prop({ context: 'platforms' }) _platforms: PlatformConfig[];
  @Prop({ context: 'readQueryParam'}) readQueryParam: (url: string, key: string) => string;
  @Element() el: HTMLElement;

  /**
   * Depending on the platform the user is on, `is(platformName)` will
   * return `true` or `false`. Note that the same app can return `true`
   * for more than one platform name. For example, an app running from
   * an iPad would return `true` for the platform names: `mobile`,
   * `ios`, `ipad`, and `tablet`. Additionally, if the app was running
   * from Cordova then `cordova` would be true, and if it was running
   * from a web browser on the iPad then `mobileweb` would be `true`.
   *
   * *
   * ```
   * import { Platform } from 'ionic-angular';
   *
   * @Component({...})
   * export MyPage {
   *   constructor(public platform: Platform) {
   *     if (this.platform.is('ios')) {
   *       // This will only print when on iOS
   *       console.log('I am an iOS device!');
   *     }
   *   }
   * }
   * ```
   *
   * | Platform Name   | Description                        |
   * |-----------------|------------------------------------|
   * | android         | on a device running Android.       |
   * | cordova         | on a device running Cordova.       |
   * | core            | on a desktop device.               |
   * | ios             | on a device running iOS.           |
   * | ipad            | on an iPad device.                 |
   * | iphone          | on an iPhone device.               |
   * | mobile          | on a mobile device.                |
   * | mobileweb       | in a browser on a mobile device.   |
   * | phablet         | on a phablet device.               |
   * | tablet          | on a tablet device.                |
   * | windows         | on a device running Windows.       |
   *
   * @param {string} platformName
   */
  @Method()
  is(platformName: string): boolean {
    for (const platform of this._platforms) {
      if (platform.name === platformName) {
        return true;
      }
    }
    return false;
  }

  /**
   * @returns {array} the array of platforms
   * @description
   * Depending on what device you are on, `platforms` can return multiple values.
   * Each possible value is a hierarchy of platforms. For example, on an iPhone,
   * it would return `mobile`, `ios`, and `iphone`.
   *
   * ```
   * import { Platform } from 'ionic-angular';
   *
   * @Component({...})
   * export MyPage {
   *   constructor(public platform: Platform) {
   *     // This will print an array of the current platforms
   *     console.log(this.platform.platforms());
   *   }
   * }
   * ```
   */
  @Method()
  platforms() {
    return this._platforms.map(platform => platform.name);
  }

  @Method()
  versions() {
    return this._platforms;
  }

  /**
   * Returns whether the device is in landscape orientation
   */
  @Method()
  isLandscape(): boolean {
    return !this.isPortrait();
  }

  /**
   * Returns whether the device is in portration orientation
   */
  @Method()
  isPortrait(): boolean {
    return window.matchMedia('(orientation: portrait)').matches;
  }

  @Method()
  ready() {
    // revisit this later on
    if (isCordova()) {
      const cordovaPlatform = this.el.querySelector('ion-cordova-plaform') as any;
      return cordovaPlatform.componentOnReady().then(() => {
        return cordovaPlatform.ready();
      });
    }
    return Promise.resolve();
  }

  @Method()
  getQueryParam(param: string): string {
    return this.readQueryParam(window.location.href, param);
  }

  render() {
    return [
      <ion-cordova-platform/>
    ];
  }

}

// angular/src/providers/platform.ts

import { PlatformConfig } from '@ionic/core';
import { EventEmitter, Injectable } from '@angular/core';
import { proxyEvent } from '../util/util';

@Injectable()
export class Platform {

  private _platforms: PlatformConfig[] = [];
  private _readyPromise: Promise<any>;

  /**
   * @hidden
   */
  backButton = new EventEmitter<Event>();

  /**
   * The pause event emits when the native platform puts the application
   * into the background, typically when the user switches to a different
   * application. This event would emit when a Cordova app is put into
   * the background, however, it would not fire on a standard web browser.
   */
  pause = new EventEmitter<Event>();

  /**
   * The resume event emits when the native platform pulls the application
   * out from the background. This event would emit when a Cordova app comes
   * out from the background, however, it would not fire on a standard web browser.
   */
  resume = new EventEmitter<Event>();

  /**
   * The resize event emits when the browser window has changed dimensions. This
   * could be from a browser window being physically resized, or from a device
   * changing orientation.
   */
  resize = new EventEmitter<Event>();

  constructor() {

    proxyEvent(this.pause, document, 'pause');
    proxyEvent(this.resume, document, 'resume');
    proxyEvent(this.backButton, document, 'backbutton');
    proxyEvent(this.resize, document, 'resize');

    let readyResolve: Function;
    this._readyPromise = new Promise(res => { readyResolve = res; } );
    if ((window as any)['cordova']) {
      window.addEventListener('deviceready', () => {
        readyResolve();
      });
    } else {
      readyResolve();
    }
  }

  /**
   * @returns {boolean} returns true/false based on platform.
   * @description
   * Depending on the platform the user is on, `is(platformName)` will
   * return `true` or `false`. Note that the same app can return `true`
   * for more than one platform name. For example, an app running from
   * an iPad would return `true` for the platform names: `mobile`,
   * `ios`, `ipad`, and `tablet`. Additionally, if the app was running
   * from Cordova then `cordova` would be true, and if it was running
   * from a web browser on the iPad then `mobileweb` would be `true`.
   *
   * ```
   * import { Platform } from 'ionic-angular';
   *
   * @Component({...})
   * export MyPage {
   *   constructor(public platform: Platform) {
   *     if (this.platform.is('ios')) {
   *       // This will only print when on iOS
   *       console.log('I am an iOS device!');
   *     }
   *   }
   * }
   * ```
   *
   * | Platform Name   | Description                        |
   * |-----------------|------------------------------------|
   * | android         | on a device running Android.       |
   * | cordova         | on a device running Cordova.       |
   * | core            | on a desktop device.               |
   * | ios             | on a device running iOS.           |
   * | ipad            | on an iPad device.                 |
   * | iphone          | on an iPhone device.               |
   * | mobile          | on a mobile device.                |
   * | mobileweb       | in a browser on a mobile device.   |
   * | phablet         | on a phablet device.               |
   * | tablet          | on a tablet device.                |
   * | windows         | on a device running Windows.       |
   * | electron        | in Electron on a desktop device.   |
   *
   * @param {string} platformName
   */
  is(platformName: string): boolean {
    return this._platforms.some(p => p.name === platformName);
  }

  /**
   * @returns {array} the array of platforms
   * @description
   * Depending on what device you are on, `platforms` can return multiple values.
   * Each possible value is a hierarchy of platforms. For example, on an iPhone,
   * it would return `mobile`, `ios`, and `iphone`.
   *
   * ```
   * import { Platform } from 'ionic-angular';
   *
   * @Component({...})
   * export MyPage {
   *   constructor(public platform: Platform) {
   *     // This will print an array of the current platforms
   *     console.log(this.platform.platforms());
   *   }
   * }
   * ```
   */
  platforms(): string[] {
    return this._platforms.map(platform => platform.name);
  }

  /**
   * Returns an object containing version information about all of the platforms.
   *
   * ```
   * import { Platform } from 'ionic-angular';
   *
   * @Component({...})
   * export MyPage {
   *   constructor(public platform: Platform) {
   *     // This will print an object containing
   *     // all of the platforms and their versions
   *     console.log(platform.versions());
   *   }
   * }
   * ```
   *
   * @returns {object} An object containing all of the platforms and their versions.
   */
  versions(): PlatformConfig[] {
    return this._platforms.slice();
  }


  ready(): Promise<void> {
    return this._readyPromise;
  }

  get isRTL(): boolean {
    return document.dir === 'rtl';
  }


  /**
   * Get the query string parameter
   */
  getQueryParam(key: string): string {
    return readQueryParam(window.location.href, key);
  }

  isLandscape(): boolean {
    return !this.isPortrait();
  }

  isPortrait(): boolean {
    return window.matchMedia('(orientation: portrait)').matches;
  }

  testUserAgent(expression: string): boolean {
    return navigator.userAgent.indexOf(expression) >= 0;
  }

  url() {
    return window.location.href;
  }

  width() {
    return window.innerWidth;
  }

  height(): number {
    return window.innerHeight;
  }
}

function readQueryParam(url: string, key: string) {
  key = key.replace(/[\[]/, '\\[').replace(/[\]]/, '\\]');
  const regex = new RegExp('[\\?&]' + key + '=([^&#]*)');
  const results = regex.exec(url);
  return results ? decodeURIComponent(results[1].replace(/\+/g, ' ')) : null;
}
