// demos/angular/src/app/simple-nav/page-one/page-one.ts
import { Component, ViewEncapsulation } from '@angular/core';
import { NavController } from '@ionic/angular';

import { PageTwo } from '../page-two/page-two';

@Component({
  selector: 'page-one',
  template: `
  <ion-page>
    <ion-header>
      <ion-toolbar>
        <ion-title>Simple Page One</ion-title>
      </ion-toolbar>
    </ion-header>
    <ion-content padding>
      Page One - {{ts}}
      <div>
        <ion-button (click)="pushPageTwoComponent()">Go to Page Two</ion-button>
      </div>
    </ion-content>
  </ion-page>
  `
})
export class PageOne {

  ts: number;
  constructor(private navController: NavController) {
    setInterval(() => {
      this.ts = Date.now();
    }, 500);
  }


  pushPageTwoComponent() {
    this.navController.push('/simple-nav/page-two');
  }



}

// packages/core/scripts/test-components/src/components/page-one/page-one.tsx
import { Component } from '@stencil/core';

@Component({
  tag: 'page-one',
})
export class PageOne {

  render() {
    return [
      <ion-page>
        <ion-header>
          <ion-toolbar>
            <ion-title>Page One</ion-title>
          </ion-toolbar>
        </ion-header>
        <ion-content>
          page one
          <a href='#/two/second-page'>Ir a la page 2</a>
        </ion-content>
      </ion-page>
    ];
  }
}
