// packages/vue/test-app/src/views/tabs/primary/children/Tab1.vue
<template>
  <ion-page data-pageid="tab1">
    <ion-header>
      <ion-toolbar>
        <ion-buttons>
          <ion-back-button default-href="/"></ion-back-button>
        </ion-buttons>
        <ion-title>Tab 1</ion-title>
      </ion-toolbar>
    </ion-header>
    <ion-content :fullscreen="true">
      <ion-header collapse="condense">
        <ion-toolbar>
          <ion-title size="large">Tab 1</ion-title>
        </ion-toolbar>
      </ion-header>

      <ExploreContainer name="Tab 1 page" />

      <ion-item button router-link="/tabs/tab1/child-one" id="child-one">
        <ion-label>Go to Tab 1 Child 1</ion-label>
      </ion-item>

      <ion-item button router-link="/nested" id="nested">
        <ion-label>Go to Nested Outlet</ion-label>
      </ion-item>

      <ion-item button router-link="/tabs-secondary" id="tabs-secondary">
        <ion-label>Go to Secondary Tabs</ion-label>
      </ion-item>

      <ion-item button router-link="/tabs" id="tabs-primary">
        <ion-label>Go to Primary Tabs</ion-label>
      </ion-item>

      <ion-item router-link="/tabs/tab1/child-one?key=value" id="child-one-query-string">
        <ion-label>Go to Tab 1 Child 1 with Query Params</ion-label>
      </ion-item>

      <ion-item @click="this.goHome" id="home">
        <ion-label>GO HOME</ion-label>
      </ion-item>
    </ion-content>
  </ion-page>
</template>

<script>
import { IonButtons, IonBackButton, IonPage, IonHeader, IonItem, IonLabel, IonToolbar, IonTitle, IonContent } from '@ionic/vue';
import ExploreContainer from '@/components/ExploreContainer.vue';

export default  {
  name: 'Tab1',
  components: { IonButtons, IonBackButton, ExploreContainer, IonHeader, IonItem, IonLabel, IonToolbar, IonTitle, IonContent, IonPage },
  methods: {
    goHome(){
      this.$router.push('/');
    }
  }
}
</script>

// packages/react-router/test-app/src/pages/routing/Tab1.tsx
import React, { useEffect } from 'react';
import { IonContent, IonHeader, IonPage, IonTitle, IonToolbar, IonList, IonItem, IonLabel, useIonViewWillEnter, useIonViewWillLeave, useIonViewDidEnter, IonButtons, IonMenuButton, IonInput } from '@ionic/react';
import './Tab1.css';
import { Link } from 'react-router-dom';

const Tab1: React.FC = () => {

  useEffect(() => {
    console.log('Home mount');
    return () => console.log('Home unmount');
  }, []);

  useIonViewWillEnter(() => {
    console.log('IVWE on tab1');
  })

  // useIonViewDidEnter(() => {
  //   console.log('IVDE on tab1');
  // })

  // useIonViewWillLeave(() => {
  //   console.log('IVWL tab1')
  // })

  return (
    <IonPage id="home" data-pageid="home-page">
      <IonHeader>
        <IonToolbar>
          <IonButtons slot="start">
            <IonMenuButton />
          </IonButtons>
          <IonTitle>Home</IonTitle>
        </IonToolbar>
      </IonHeader>
      <IonContent>  
        <IonList>
          <IonItem routerLink='/routing/tabs/home/details/1'>
            <IonLabel>Details 1</IonLabel>
          </IonItem>
          <IonItem routerLink='/routing/tabs/home/details/1?hello=there'>
            <IonLabel>Details 1 with Query Params</IonLabel>
          </IonItem>
          <IonItem routerLink='/routing/tabs/settings/details/1'>
            <IonLabel>Details 1 on settings</IonLabel>
          </IonItem>
          <IonItem routerLink='/routing/otherpage'>
            <IonLabel>Other Page</IonLabel>
          </IonItem>
        </IonList>
        <Link to="/routing/tabs/home/details/1">
          Go to details 1 via link
        </Link>
        <br /><br />
        <Link to="/routing/tabs/settings/details/1">
          Go to details 1 on settings
        </Link>
      </IonContent>
    </IonPage>
  );
};

export default Tab1;
