// packages/vue/test-app/src/views/Tab2.vue
<template>
  <ion-page data-pageid="tab2">
    <ion-header>
      <ion-toolbar>
        <ion-title>Tab 2</ion-title>
      </ion-toolbar>
    </ion-header>
    <ion-content :fullscreen="true">
      <ion-header collapse="condense">
        <ion-toolbar>
          <ion-title size="large">Tab 2</ion-title>
        </ion-toolbar>
      </ion-header>

      <ion-item button router-link="/routing" id="routing">
        <ion-label>Go to /routing</ion-label>
      </ion-item>
    </ion-content>
  </ion-page>
</template>

<script>
  import { IonItem, IonLabel, IonPage, IonHeader, IonToolbar, IonTitle, IonContent } from '@ionic/vue';

  export default {
    components: { IonItem, IonLabel, IonHeader, IonToolbar, IonTitle, IonContent, IonPage }
  }
</script>

// packages/react-router/test-app/src/pages/routing/Tab2.tsx
import React, { useEffect } from 'react';
import { IonContent, IonHeader, IonPage, IonTitle, IonToolbar, IonList, IonItem, IonLabel, IonButtons, IonMenuButton } from '@ionic/react';
import './Tab2.css';

const Tab2: React.FC = () => {

  useEffect(() => {
    console.log('Settings mount');
    return () => console.log('Settings unmount');
  }, []);


  return (
    <IonPage data-pageid="settings-page">
      <IonHeader translucent={true}>
        <IonToolbar>
          <IonButtons slot="start">
            <IonMenuButton />
          </IonButtons>
          <IonTitle>Settings</IonTitle>
        </IonToolbar>
      </IonHeader>
      <IonContent>
      <IonHeader collapse="condense">
          <IonToolbar>
            <IonTitle size="large">Settings</IonTitle>
          </IonToolbar>
        </IonHeader>
        <IonList>
          <IonItem routerLink='/routing/tabs/settings/details/1'>
            <IonLabel>Settings Details 1</IonLabel>
          </IonItem>
          <IonItem routerLink='/routing/tabs/settings/details/2'>
            <IonLabel>Settings Details 2</IonLabel>
          </IonItem>
        </IonList>
      </IonContent>
    </IonPage>
  );
};

export default Tab2;
