// packages/ionic-angular/src/components/searchbar/searchbar.ts
import { Component, ElementRef, EventEmitter, Input, Optional, Output, Renderer, ViewChild, ViewEncapsulation } from '@angular/core';
import { NgControl } from '@angular/forms';

import { Config } from '../../config/config';
import { BaseInput } from '../../util/base-input';
import { isPresent, isTrueProperty } from '../../util/util';
import { TimeoutDebouncer } from '../../util/debouncer';
import { Platform } from '../../platform/platform';

/**
 * @name Searchbar
 * @module ionic
 * @description
 * Manages the display of a Searchbar which can be used to search or filter items.
 *
 * @usage
 * ```html
 * <ion-searchbar
 *   [(ngModel)]="myInput"
 *   [showCancelButton]="shouldShowCancel"
 *   (ionInput)="onInput($event)"
 *   (ionCancel)="onCancel($event)">
 * </ion-searchbar>
 * ```
 *
 * @demo /docs/demos/src/searchbar/
 * @see {@link /docs/components#searchbar Searchbar Component Docs}
 */
@Component({
  selector: 'ion-searchbar',
  template:
    '<div class="searchbar-input-container">' +
      '<ion-button mode="md" (click)="cancelSearchbar($event)" (mousedown)="cancelSearchbar($event)" clear color="dark" class="searchbar-md-cancel" type="button">' +
        '<ion-icon name="md-arrow-back"></ion-icon>' +
      '</ion-button>' +
      '<div #searchbarIcon class="searchbar-search-icon"></div>' +
      '<input #searchbarInput class="searchbar-input" (input)="inputChanged($event)" (blur)="inputBlurred()" (focus)="inputFocused()" ' +
        '[attr.placeholder]="placeholder" ' +
        '[attr.type]="type" ' +
        '[attr.autocomplete]="_autocomplete" ' +
        '[attr.autocorrect]="_autocorrect" ' +
        '[attr.spellcheck]="_spellcheck">' +
      '<ion-button clear class="searchbar-clear-icon" [mode]="_mode" (click)="clearInput($event)" (mousedown)="clearInput($event)" type="button"></ion-button>' +
    '</div>' +
    '<ion-button #cancelButton mode="ios" [tabindex]="_isActive ? 1 : -1" clear (click)="cancelSearchbar($event)" (mousedown)="cancelSearchbar($event)" class="searchbar-ios-cancel" type="button">{{cancelButtonText}}</ion-button>',
  host: {
    '[class.searchbar-animated]': '_animated',
    '[class.searchbar-has-value]': '_value',
    '[class.searchbar-active]': '_isActive',
    '[class.searchbar-show-cancel]': '_showCancelButton',
    '[class.searchbar-left-aligned]': '_shouldAlignLeft',
    '[class.searchbar-has-focus]': '_isFocus'
  },
  encapsulation: ViewEncapsulation.None
})
export class Searchbar extends BaseInput<string> {

  _shouldBlur: boolean = true;
  _shouldAlignLeft: boolean = true;
  _isCancelVisible: boolean = false;
  _spellcheck: boolean = false;
  _autocomplete: string = 'off';
  _autocorrect: string = 'off';
  _isActive: boolean = false;
  _showCancelButton: boolean = false;
  _animated: boolean = false;
  _inputDebouncer: TimeoutDebouncer = new TimeoutDebouncer(0);

  /**
   * @input {string} Set the the cancel button text. Default: `"Cancel"`.
   */
  @Input() cancelButtonText: string = 'Cancel';

  /**
   * @input {boolean} If true, show the cancel button. Default `false`.
   */
  @Input()
  get showCancelButton(): boolean {
    return this._showCancelButton;
  }
  set showCancelButton(val: boolean) {
    this._showCancelButton = isTrueProperty(val);
  }

  /**
   * @input {number} How long, in milliseconds, to wait to trigger the `ionInput` event after each keystroke. Default `250`.
   */
  @Input()
  get debounce(): number {
    return this._debouncer.wait;
  }
  set debounce(val: number) {
    this._debouncer.wait = val;
    this._inputDebouncer.wait = val;
  }

  /**
   * @input {string} Set the input's placeholder. Default `"Search"`.
   */
  @Input() placeholder: string = 'Search';

  /**
   * @input {string} Set the input's autocomplete property. Values: `"on"`, `"off"`. Default `"off"`.
   */
  @Input()
  set autocomplete(val: string) {
    this._autocomplete = (val === '' || val === 'on') ? 'on' : this._config.get('autocomplete', 'off');
  }

  /**
   * @input {string} Set the input's autocorrect property. Values: `"on"`, `"off"`. Default `"off"`.
   */
  @Input()
  set autocorrect(val: string) {
    this._autocorrect = (val === '' || val === 'on') ? 'on' : this._config.get('autocorrect', 'off');
  }

  /**
   * @input {string|boolean} Set the input's spellcheck property. Values: `true`, `false`. Default `false`.
   */
  @Input()
  set spellcheck(val: string | boolean) {
    this._spellcheck = (val === '' || val === 'true' || val === true) ? true : this._config.getBoolean('spellcheck', false);
  }

  /**
   * @input {string} Set the type of the input. Values: `"text"`, `"password"`, `"email"`, `"number"`, `"search"`, `"tel"`, `"url"`. Default `"search"`.
   */
  @Input() type: string = 'search';

  /**
   * @input {boolean} If true, enable searchbar animation. Default `false`.
   */
  @Input()
  get animated(): boolean {
    return this._animated;
  }
  set animated(val: boolean) {
    this._animated = isTrueProperty(val);
  }

  /**
   * @output {event} Emitted when the Searchbar input has changed, including when it's cleared.
   */
  @Output() ionInput: EventEmitter<UIEvent> = new EventEmitter<UIEvent>();

  /**
   * @output {event} Emitted when the cancel button is clicked.
   */
  @Output() ionCancel: EventEmitter<UIEvent> = new EventEmitter<UIEvent>();

  /**
   * @output {event} Emitted when the clear input button is clicked.
   */
  @Output() ionClear: EventEmitter<UIEvent> = new EventEmitter<UIEvent>();


  constructor(
    config: Config,
    private _plt: Platform,
    elementRef: ElementRef,
    renderer: Renderer,
    @Optional() ngControl: NgControl
  ) {
    super(config, elementRef, renderer, 'searchbar', '', null, null, ngControl);
    this.debounce = 250;
  }

  @ViewChild('searchbarInput') _searchbarInput: ElementRef;

  @ViewChild('searchbarIcon') _searchbarIcon: ElementRef;

  @ViewChild('cancelButton', {read: ElementRef}) _cancelButton: ElementRef;

  /**
   * @hidden
   * On Initialization check for attributes
   */
  ngOnInit() {
    const showCancelButton = this.showCancelButton;
    if (typeof showCancelButton === 'string') {
      this.showCancelButton = (showCancelButton === '' || showCancelButton === 'true');
    }
  }

  /**
   * @hidden
   */
  _inputUpdated() {
    const ele = this._searchbarInput.nativeElement;
    // It is important not to re-assign the value if it is the same, because,
    // otherwise, the caret is moved to the end of the input
    if (ele && ele.value !== this.value) {
      ele.value = this.value;
    }
    this.positionElements();
  }

  /**
   * @hidden
   * Positions the input search icon, placeholder, and the cancel button
   * based on the input value and if it is focused. (ios only)
   */
  positionElements() {
    const isAnimated = this._animated;
    const prevAlignLeft = this._shouldAlignLeft;
    const shouldAlignLeft = (!isAnimated || (this._value && this._value.toString().trim() !== '') || this._isFocus === true);
    this._shouldAlignLeft = shouldAlignLeft;

    if (this._mode !== 'ios') {
      return;
    }

    if (prevAlignLeft !== shouldAlignLeft) {
      this.positionPlaceholder();
    }
    if (isAnimated) {
      this.positionCancelButton();
    }
  }

  positionPlaceholder() {
    const inputEle = this._searchbarInput.nativeElement;
    const iconEle = this._searchbarIcon.nativeElement;

    if (this._shouldAlignLeft) {
      inputEle.removeAttribute('style');
      iconEle.removeAttribute('style');

    } else {
      // Create a dummy span to get the placeholder width
      var doc = this._plt.doc();
      var tempSpan = doc.createElement('span');
      tempSpan.innerHTML = this.placeholder;
      doc.body.appendChild(tempSpan);

      // Get the width of the span then remove it
      var textWidth = tempSpan.offsetWidth;
      doc.body.removeChild(tempSpan);

      // Set the input padding start
      var inputLeft = 'calc(50% - ' + (textWidth / 2) + 'px)';
      if (this._plt.isRTL) {
        inputEle.style.paddingRight = inputLeft;
      } else {
        inputEle.style.paddingLeft = inputLeft;
      }

      // Set the icon margin start
      var iconLeft = 'calc(50% - ' + ((textWidth / 2) + 30) + 'px)';
      if (this._plt.isRTL) {
        iconEle.style.marginRight = iconLeft;
      } else {
        iconEle.style.marginLeft = iconLeft;
      }
    }
  }

  /**
   * @hidden
   * Show the iOS Cancel button on focus, hide it offscreen otherwise
   */
  positionCancelButton() {
    const showShowCancel = this._isFocus;
    if (showShowCancel !== this._isCancelVisible) {
      var cancelStyleEle = this._cancelButton.nativeElement;
      var cancelStyle = cancelStyleEle.style;
      this._isCancelVisible = showShowCancel;
      if (showShowCancel) {
        if (this._plt.isRTL) {
          cancelStyle.marginLeft = '0';
        } else {
          cancelStyle.marginRight = '0';
        }
      } else {
        var offset = cancelStyleEle.offsetWidth;
        if (offset > 0) {
          if (this._plt.isRTL) {
            cancelStyle.marginLeft = -offset + 'px';
          } else {
            cancelStyle.marginRight = -offset + 'px';
          }
        }
      }
    }
  }


  /**
   * @hidden
   * Update the Searchbar input value when the input changes
   */
  inputChanged(ev: any) {
    this.value = ev.target.value;
    this._inputDebouncer.debounce(() => {
      this.ionInput.emit(ev);
    });
  }

  /**
   * @hidden
   * Sets the Searchbar to focused and active on input focus.
   */
  inputFocused() {
    this._isActive = true;
    this._fireFocus();
    this.positionElements();
  }

  /**
   * @hidden
   * Sets the Searchbar to not focused and checks if it should align left
   * based on whether there is a value in the searchbar or not.
   */
  inputBlurred() {
    // _shouldBlur determines if it should blur
    // if we are clearing the input we still want to stay focused in the input
    if (this._shouldBlur === false) {
      this._searchbarInput.nativeElement.focus();
      this._shouldBlur = true;
      return;
    }
    this._fireBlur();
    this.positionElements();
  }

  /**
   * @hidden
   * Clears the input field and triggers the control change.
   */
  clearInput(ev: UIEvent) {
    this.ionClear.emit(ev);

    // setTimeout() fixes https://github.com/ionic-team/ionic/issues/7527
    // wait for 4 frames
    setTimeout(() => {
      let value = this._value;
      if (isPresent(value) && value !== '') {
        this.value = ''; // DOM WRITE
        this.ionInput.emit(ev);
      }
    }, 16 * 4);
    this._shouldBlur = false;
  }

  /**
   * @hidden
   * Clears the input field and tells the input to blur since
   * the clearInput function doesn't want the input to blur
   * then calls the custom cancel function if the user passed one in.
   */
  cancelSearchbar(ev: UIEvent) {
    this.ionCancel.emit(ev);

    this.clearInput(ev);
    this._shouldBlur = true;
    this._isActive = false;
  }

  setFocus() {
    this._renderer.invokeElementMethod(this._searchbarInput.nativeElement, 'focus');
  }

}

// packages/core/src/components/searchbar/searchbar.tsx
import { Component, Element, Event, EventEmitter, Prop, State } from '@stencil/core';


/**
 * @name Searchbar
 * @module ionic
 * @description
 * Manages the display of a Searchbar which can be used to search or filter items.
 *
 * @usage
 * ```html
 * <ion-searchbar
 *   [(ngModel)]="myInput"
 *   [showCancelButton]="shouldShowCancel"
 *   (ionInput)="onInput($event)"
 *   (ionCancel)="onCancel($event)">
 * </ion-searchbar>
 * ```
 *
 * @demo /docs/demos/src/searchbar/
 * @see {@link /docs/components#searchbar Searchbar Component Docs}
 */
@Component({
  tag: 'ion-searchbar',
  styleUrls: {
    ios: 'searchbar.ios.scss',
    md: 'searchbar.md.scss',
    wp: 'searchbar.wp.scss'
  },
  host: {
    theme: 'searchbar'
  }
})
export class Searchbar {
  private _isCancelVisible: boolean = false;
  private _shouldBlur: boolean = true;
  private _shouldAlignLeft: boolean = true;

  @Element() el: HTMLElement;

  @Prop() mode: string;

  @Prop() color: string;

  @State() activated: boolean = false;

  @State() focused: boolean = false;


  /**
   * @output {event} Emitted when the Searchbar input has changed, including when it's cleared.
   */
  @Event() ionInput: EventEmitter;

  /**
   * @output {event} Emitted when the cancel button is clicked.
   */
  @Event() ionCancel: EventEmitter;

  /**
   * @output {event} Emitted when the clear input button is clicked.
   */
  @Event() ionClear: EventEmitter;

  /**
   * @output {event}
   */
  @Event() ionBlur: EventEmitter;

  /**
   * @output {event}
   */
  @Event() ionFocus: EventEmitter;


  /**
   * @input {boolean} If true, enable searchbar animation. Default `false`.
   */
  @Prop({ mutable: true }) animated: boolean = false;

  /**
   * @input {string} Set the input's autocomplete property. Values: `"on"`, `"off"`. Default `"off"`.
   */
  @Prop({ mutable: true }) autocomplete: string = 'off';

  /**
   * @input {string} Set the input's autocorrect property. Values: `"on"`, `"off"`. Default `"off"`.
   */
  @Prop({ mutable: true }) autocorrect: string = 'off';

  /**
   * @input {string} Set the the cancel button text. Default: `"Cancel"`.
   */
  @Prop({ mutable: true }) cancelButtonText: string = 'Cancel';


//   _inputDebouncer: TimeoutDebouncer = new TimeoutDebouncer(0);

//   /**
//    * @input {number} How long, in milliseconds, to wait to trigger the `ionInput` event after each keystroke. Default `250`.
//    */
//   @Input()
//   get debounce(): number {
//     return this._debouncer.wait;
//   }
//   set debounce(val: number) {
//     this._debouncer.wait = val;
//     this._inputDebouncer.wait = val;
//   }

  /**
   * @input {number} Set the amount of time, in milliseconds, to wait to trigger the `ionInput` event after each keystroke. Default `250`.
   */
  @Prop({ mutable: true }) debounce: number = 250;

  /**
   * @input {string} Set the input's placeholder. Default `"Search"`.
   */
  @Prop({ mutable: true }) placeholder: string = 'Search';

  /**
   * @input {boolean} If true, show the cancel button. Default `false`.
   */
  @Prop({ mutable: true }) showCancelButton: boolean = false;

  /**
   * @input {boolean} If true, enable spellcheck on the input. Default `false`.
   */
  @Prop({ mutable: true }) spellcheck: boolean = false;

  /**
   * @input {string} Set the type of the input. Values: `"text"`, `"password"`, `"email"`, `"number"`, `"search"`, `"tel"`, `"url"`. Default `"search"`.
   */
  @Prop({ mutable: true }) type: string = 'search';

  /**
   * @input {string} Set the value of the searchbar.
   */
  @Prop({ mutable: true }) value: string;


  ionViewDidLoad() {
    this.positionElements();
  }

  /**
   * @hidden
   * Clears the input field and triggers the control change.
   */
  clearInput(ev: UIEvent) {
    this.ionClear.emit({event: ev});

    // setTimeout() fixes https://github.com/ionic-team/ionic/issues/7527
    // wait for 4 frames
    setTimeout(() => {
      let value = this.value;
      if (value !== undefined && value !== '') {
        this.value = '';
        this.ionInput.emit({event: ev});
      }
    }, 16 * 4);
    this._shouldBlur = false;
  }

  /**
   * @hidden
   * Clears the input field and tells the input to blur since
   * the clearInput function doesn't want the input to blur
   * then calls the custom cancel function if the user passed one in.
   */
  cancelSearchbar(ev: UIEvent) {
    this.ionCancel.emit({event: ev});

    this.clearInput(ev);
    this._shouldBlur = true;
    this.activated = false;
  }

  /**
   * @hidden
   * Update the Searchbar input value when the input changes
   */
  inputChanged(ev: any) {
    this.value = ev.target.value;
    // this._inputDebouncer.debounce(() => {
    // TODO fix to be inside debounce
    this.ionInput.emit(ev);
    // });
  }

  /**
   * @hidden
   */
  inputUpdated() {
    // const inputEle = this.el.querySelector('.searchbar-input') as HTMLInputElement;

    // It is important not to re-assign the value if it is the same, because,
    // otherwise, the caret is moved to the end of the input
    // if (inputEle && inputEle.value !== this.value) {
    //   // inputEle.value = this.value;
    //   this.value = inputEle.value;
    // }

    this.positionElements();
  }

  /**
   * @hidden
   * Sets the Searchbar to not focused and checks if it should align left
   * based on whether there is a value in the searchbar or not.
   */
  inputBlurred() {
    const inputEle = this.el.querySelector('.searchbar-input') as HTMLElement;

    // _shouldBlur determines if it should blur
    // if we are clearing the input we still want to stay focused in the input
    if (this._shouldBlur === false) {
      inputEle.focus();
      this._shouldBlur = true;
      this.ionBlur.emit({this: this});
      this.inputUpdated();
      return;
    }

    this.focused = false;
    this.positionElements();
  }

  /**
   * @hidden
   * Sets the Searchbar to focused and active on input focus.
   */
  inputFocused() {
    this.activated = true;

    this.focused = true;
    this.ionFocus.emit({this: this});
    this.inputUpdated();

    this.positionElements();
  }

  /**
   * @hidden
   * Positions the input search icon, placeholder, and the cancel button
   * based on the input value and if it is focused. (ios only)
   */
  positionElements() {
    const prevAlignLeft = this._shouldAlignLeft;
    const _shouldAlignLeft = (!this.animated || (this.value && this.value.toString().trim() !== '') || this.focused === true);
    this._shouldAlignLeft = _shouldAlignLeft;

    if (this.mode !== 'ios') {
      return;
    }

    if (prevAlignLeft !== _shouldAlignLeft) {
      this.positionPlaceholder();
    }

    if (this.animated) {
      this.positionCancelButton();
    }
  }

  /**
   * @hidden
   * Positions the input placeholder
   */
  positionPlaceholder() {
    const isRTL = document.dir === 'rtl';
    const inputEle = this.el.querySelector('.searchbar-input') as HTMLElement;
    const iconEle = this.el.querySelector('.searchbar-search-icon') as HTMLElement;

    if (this._shouldAlignLeft) {
      inputEle.removeAttribute('style');
      iconEle.removeAttribute('style');

    } else {
      // Create a dummy span to get the placeholder width
      var tempSpan = document.createElement('span');
      tempSpan.innerHTML = this.placeholder;
      document.body.appendChild(tempSpan);

      // Get the width of the span then remove it
      var textWidth = tempSpan.offsetWidth;
      document.body.removeChild(tempSpan);

      // Calculate the input padding
      var inputLeft = 'calc(50% - ' + (textWidth / 2) + 'px)';

      // Calculate the icon margin
      var iconLeft = 'calc(50% - ' + ((textWidth / 2) + 30) + 'px)';

      // Set the input padding start and icon margin start
      if (isRTL) {
        inputEle.style.paddingRight = inputLeft;
        iconEle.style.marginRight = iconLeft;
      } else {
        inputEle.style.paddingLeft = inputLeft;
        iconEle.style.marginLeft = iconLeft;
      }
    }
  }

  /**
   * @hidden
   * Show the iOS Cancel button on focus, hide it offscreen otherwise
   */
  positionCancelButton() {
    const isRTL = document.dir === 'rtl';
    const cancelButton = this.el.querySelector('.searchbar-ios-cancel') as HTMLElement;
    const shouldShowCancel = this.focused;

    if (shouldShowCancel !== this._isCancelVisible) {
      var cancelStyle = cancelButton.style;
      this._isCancelVisible = shouldShowCancel;
      if (shouldShowCancel) {
        if (isRTL) {
          cancelStyle.marginLeft = '0';
        } else {
          cancelStyle.marginRight = '0';
        }
      } else {
        var offset = cancelButton.offsetWidth;
        if (offset > 0) {
          if (isRTL) {
            cancelStyle.marginLeft = -offset + 'px';
          } else {
            cancelStyle.marginRight = -offset + 'px';
          }
        }
      }
    }
  }

  hostData() {
    return {
      class: {
        'searchbar-active': this.activated,
        'searchbar-animated': this.animated,
        'searchbar-has-value': (this.value !== undefined && this.value !== ''),
        'searchbar-show-cancel': this.showCancelButton,
        'searchbar-left-aligned': this._shouldAlignLeft,
        'searchbar-has-focus': this.focused
      }
    };
  }

  render() {
    return [
      <div class='searchbar-input-container'>
        <ion-button
          mode='md'
          onClick={this.cancelSearchbar.bind(this)}
          onMousedown={this.cancelSearchbar.bind(this)}
          clear
          color='dark'
          class='searchbar-md-cancel'>
            <ion-icon name='md-arrow-back'></ion-icon>
        </ion-button>
        <div class='searchbar-search-icon'></div>
        <input
          class='searchbar-input'
          onInput={this.inputChanged.bind(this)}
          onBlur={this.inputBlurred.bind(this)}
          onFocus={this.inputFocused.bind(this)}
          placeholder={this.placeholder}
          type={this.type}
          value={this.value}
          autoComplete={this.autocomplete}
          autoCorrect={this.autocorrect}
          spellCheck={this.spellcheck}/>
        <ion-button
          clear
          class='searchbar-clear-icon'
          onClick={this.clearInput.bind(this)}
          onMousedown={this.clearInput.bind(this)}>
        </ion-button>
      </div>,
      <ion-button
        tabindex={this.activated ? 1 : -1}
        clear
        onClick={this.cancelSearchbar.bind(this)}
        onMousedown={this.cancelSearchbar.bind(this)}
        class='searchbar-ios-cancel'>
          {this.cancelButtonText}
      </ion-button>
    ];
  }
}
