// core/src/components/infinite-scroll-content/infinite-scroll-content.tsx
import { Component, Prop } from '@stencil/core';
import { Config } from '../../interface';


@Component({
  tag: 'ion-infinite-scroll-content',
  styleUrls: {
    ios: 'infinite-scroll-content.ios.scss',
    md: 'infinite-scroll-content.md.scss'
  },
  host: {
    theme: 'infinite-scroll-content'
  }
})
export class InfiniteScrollContent {

  @Prop({ context: 'config' }) config!: Config;

  /**
   * An animated SVG spinner that shows while loading.
   */
  @Prop({ mutable: true }) loadingSpinner?: string;

  /**
   * Optional text to display while loading.
   */
  @Prop() loadingText?: string;


  componentDidLoad() {
    if (!this.loadingSpinner) {
      this.loadingSpinner = this.config.get('infiniteLoadingSpinner', this.config.get('spinner', 'lines'));
    }
  }

  render() {
    return (
      <div class="infinite-loading">
        {this.loadingSpinner &&
          <div class="infinite-loading-spinner">
            <ion-spinner name={this.loadingSpinner}></ion-spinner>
          </div>
        }
        {this.loadingText &&
          <div class="infinite-loading-text" innerHTML={this.loadingText}></div>
        }
      </div>
    );
  }
}

// packages/ionic-angular/src/components/infinite-scroll/infinite-scroll-content.ts
import { Component, Input, ViewEncapsulation } from '@angular/core';

import { Config } from '../../config/config';
import { InfiniteScroll } from './infinite-scroll';


/**
 * @hidden
 */
@Component({
  selector: 'ion-infinite-scroll-content',
  template:
    '<div class="infinite-loading">' +
      '<div class="infinite-loading-spinner" *ngIf="loadingSpinner">' +
        '<ion-spinner [name]="loadingSpinner"></ion-spinner>' +
      '</div>' +
      '<div class="infinite-loading-text" [innerHTML]="loadingText" *ngIf="loadingText"></div>' +
    '</div>',
  host: {
    '[attr.state]': 'inf.state'
  },
  encapsulation: ViewEncapsulation.None,
})
export class InfiniteScrollContent {

  /**
   * @input {string} An animated SVG spinner that shows while loading.
   */
  @Input() loadingSpinner: string;

  /**
   * @input {string} Optional text to display while loading.
   */
  @Input() loadingText: string;

  constructor(public inf: InfiniteScroll, private _config: Config) {}

  /**
   * @hidden
   */
  ngOnInit() {
    if (!this.loadingSpinner) {
      this.loadingSpinner = this._config.get('infiniteLoadingSpinner', this._config.get('spinner', 'ios'));
    }
  }
}
